[workspace]
members = [
    "spwn",
    "parser",
    "shared",
    "errors",
    "levelstring",
    "editorlive",
    "compiler",
    "optimizer",
    "docgen",
    "spwn-web",
    "pckp"
]

[profile.dev]
debug-assertions = true
opt-level = 2

[profile.test]
debug-assertions = false
opt-level = 2