[workspace]
members = [
    "spwn",
    "parser",
    "shared",
    "errors",
    "levelstring",
    "editorlive",
    "compiler",
    "optimizer",
    "docgen",
    "spwn-web",
    "pckp",
	"proc_macros",
	"libraries",
]

[profile.dev]
debug-assertions = true
opt-level = 2
