[package]
name = "libraries"
version = "0.0.7"
edition = "2021"

[dependencies]
include_dir = "0.6.2"
lazy_static = "1.4.0"

proc_macros = { path = "../proc_macros" }
shared = { path = "../shared" }

